CREATE TABLE employee (
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR2(100) NOT NULL,
    last_name   VARCHAR2(100) NOT NULL,
    email       VARCHAR2(255) NOT NULL,
    department  VARCHAR2(100),
    job_title   VARCHAR2(100),
    salary      NUMBER(15,2),
    hire_date   DATE,
    CONSTRAINT uk_employee_email UNIQUE (email)
);
